#!/usr/bin/env bash

set -euo pipefail

parent_dir="$(cd "$(dirname "$0")" && pwd)"

extract_tarball() {
  rm -rf node
  mkdir node
  tar -xf "tarball_path/node_v${version}_linux_x64_bionic_"*".tgz" -C node
}

check_version() {
  actual_version="$(./node/bin/node --version)"
  if [[ "${actual_version}" != "v${version}" ]]; then
    echo "Version ${actual_version} does not match expected version ${version}"
    exit 1
  fi
}

check_server() {
  set +e

  ./node/bin/node "${parent_dir}/fixtures/server.js" 8080 &
  server_pid=$!

  succeeded=0
  for _ in {1..5}; do
    if curl http://localhost:8080 >/dev/null 2>&1; then
      succeeded=1
      break
    fi
    sleep 1
  done

  kill "${server_pid}"

  if [[ ! "${succeeded}" ]]; then
    echo "Failed to curl server"
    exit 1
  fi

  set -e
}

main() {
  local version
  version=

  while test $# -gt 0; do
    case $1 in
      --version)
        version=$2
        shift
        ;;
      *)
        echo >&2 "Invalid argument: $1"
        exit 1
        ;;
    esac
    shift
  done

  if [[ "${version}" == "" ]]; then
    echo "Version is required"
    exit 1
  fi

  extract_tarball
  check_version
  check_server

  echo "All Node bionic dependency tests passed!"
}

main "${@:-}"
