#!/usr/bin/env bash

set -euo pipefail

main() {
  local tarball_path version

  while [ "${#}" != 0 ]; do
    case "${1}" in
      --version)
        version="${2}"
        shift 2
        ;;

      --tarballPath)
        tarball_path="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  if [[ -z "${version:-}" || -z "${tarball_path:-}" ]]; then
    echo "version and tarballPath are required required"
    exit 1
  fi

  echo "Running bionic test..."
  docker build -t test -f Dockerfile .
  docker run --rm -v "$(dirname -- "${tarball_path}"):/tarball_path" test --version "${version}"
}

main "${@:-}"
